filetype on
syntax on
colorscheme Tomorrow-Night

set hidden
set number
set history=100

filetype indent on
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set autoindent
set showmatch

map <leader>rr :source ~/.vimrc<CR>



